# Generated by Django 3.2.4 on 2021-06-19 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo_parroquia', models.CharField(choices=[('rural', 'Parroquia rural'), ('urbana', 'Parroquia Urbana')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('num_viviendas', models.IntegerField(verbose_name='Número de Viviendas')),
                ('num_parques', models.IntegerField(choices=[(1, 'Un parque'), (2, 'Dos parques'), (3, 'Tres parques'), (4, 'Cuatro parques'), (5, 'Cinco parques'), (6, 'Seis parques')], verbose_name='Número de parques')),
                ('num_edificios', models.IntegerField(verbose_name='Número de Edificios')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lasparroquias', to='administrativo.parroquia')),
            ],
        ),
    ]
